version: '3'

services:
  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - 81:80
      - 8181:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5901:5900
    volumes:
      - /dev/shm:/dev/shm
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:chrometesting.localhost

  firefox:
    image: selenium/standalone-firefox-debug:2.53.0
    ports:
      - 4445:4444
      - 5902:5900
    volumes:
      - /dev/shm:/dev/shm
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:firefoxtesting.localhost